#!/usr/bin/env python3
r"""Generate reference\mods.tsv, the committed mod manifest. Never edit it by hand.

    python scripts\gen-mods.py                  write reference\mods.tsv from the Gale profile
    python scripts\gen-mods.py --check          exit 0 = manifest matches the profile, 1 = drift
    python scripts\gen-mods.py --verify <path>  check another install against the manifest;
                                                <path> = a BepInEx\plugins folder or a LogOutput.log

Columns: id, version, plugin.
  id      Thunderstore / Hexium <Owner>-<Name>, the plugins\ folder name
  version manifest.json version_number, prerelease tag kept (KG is 10.0.1-beta.1)
  plugin  the name BepInEx logs as "Loading [<plugin> <version>]" - the only handle a
          Gale-less install (the dedicated host) exposes

Source, role and status stay in RESEARCH.md §3. Versions live here only.
"""
import glob
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'reference' / 'mods.tsv'
BEP = Path(os.environ['APPDATA']) / 'com.kesomannen.gale/valheim/profiles/OSRSheim/BepInEx'

BEPINEX_ID = 'denikson-BepInExPack_Valheim'
# Log display names that no name rule reaches from the Thunderstore id.
OVERRIDES = {'OdinPlus-PotionPlus': 'PotionsPlus',
             'ValheimModding-JsonDotNET': 'Newtonsoft.Json Detector',
             'ValheimModding-YamlDotNet': 'YamlDotNet Detector',
             BEPINEX_ID: 'BepInEx'}
# Detector shims: they log their own 1.0.0, never the packaged library version,
# so a log can only prove they are loaded.
NO_VERSION = {'ValheimModding-JsonDotNET', 'ValheimModding-YamlDotNet'}

HEADER = ("# Generated by scripts\\gen-mods.py from the Gale profile OSRSheim. Do not hand-edit.\n"
          "# id\tversion\tplugin  (plugin = the name in BepInEx's \"Loading [name version]\")\n")


def read(path):
    with open(path, encoding='utf-8-sig') as f:
        return f.read()


def norm(s):
    return re.sub(r'[^a-z0-9]', '', s.lower().replace('&', 'and'))


def version_eq(a, b):
    """1.113.0 == 1.113; 10.0.1-beta.1 == 10.0.1 (BepInEx logs no prerelease tag)."""
    if a == b:
        return True
    pa, pb = [re.split(r'[-+]', v)[0].split('.') for v in (a, b)]
    n = max(len(pa), len(pb))
    return (pa + ['0'] * n)[:n] == (pb + ['0'] * n)[:n]


def from_plugins(plugins):
    """{id: version} from a BepInEx\\plugins folder of Gale / r2modman installs."""
    out = {}
    for m in sorted(glob.glob(os.path.join(plugins, '*', 'manifest.json'))):
        d = os.path.dirname(m)
        try:
            out[os.path.basename(d)] = json.loads(read(m))['version_number']
        except Exception as e:
            print(f"unreadable {m}: {e}")
            continue
        # Gale and r2modman disable a mod by renaming its dll to .dll.old.
        if (glob.glob(os.path.join(d, '**', '*.dll.old'), recursive=True)
                and not glob.glob(os.path.join(d, '**', '*.dll'), recursive=True)):
            print(f'note     {os.path.basename(d)} is disabled (dll renamed .old) but still installed')
    return out


def from_log(log):
    """{plugin display name: version} plus the BepInEx pack, from a LogOutput.log."""
    t = read(log)
    out = dict(re.findall(r'Loading \[(.+?) (\S+)\]', t))
    m = re.search(r'BepInExPack Valheim version (\S+)', t)
    if m:
        out['BepInEx'] = m.group(1)
    return out


def plugin_names(ids, logged):
    """Map each id to its log display name: exact, prefix/suffix or override, version agreeing."""
    out = {}
    for mid, ver in ids.items():
        if mid in OVERRIDES:
            out[mid] = OVERRIDES[mid]
            continue
        key = norm(mid.split('-', 1)[1])
        hits = [n for n, v in logged.items()
                if version_eq(ver, v) and (norm(n) == key or norm(n).startswith(key) or
                                           key.startswith(norm(n)) or key.endswith(norm(n)))]
        exact = [n for n in hits if norm(n) == key]
        out[mid] = (exact or hits or [''])[0]
    return out


def build():
    """The manifest the local Gale profile implies, as file text."""
    ids = from_plugins(str(BEP / 'plugins'))
    log = BEP / 'LogOutput.log'
    logged = from_log(str(log)) if log.exists() else {}
    if 'BepInEx' in logged:
        ids[BEPINEX_ID] = logged['BepInEx']
    elif OUT.exists():  # no log to read: carry the committed pack version forward
        for mid, ver, _ in rows(read(OUT)):
            if mid == BEPINEX_ID:
                ids[mid] = ver
    names = plugin_names(ids, logged)
    missing = sorted(m for m, n in names.items() if not n)
    if missing and logged:
        print('no "Loading [...]" line matched, plugin column left empty: ' + ', '.join(missing))
    body = ''.join(f'{m}\t{ids[m]}\t{names[m]}\n' for m in sorted(ids, key=str.lower))
    return HEADER + body


def rows(text):
    for line in text.splitlines():
        if line.strip() and not line.startswith('#'):
            f = (line.split('\t') + ['', ''])[:3]
            yield f[0], f[1], f[2]


def diff(want, have, what, presence_only=()):
    """want / have are {key: version}. Returns a list of complaints."""
    out = [f'{k} {have[k]} on {what}, manifest says {v}'
           for k, v in sorted(want.items())
           if k in have and k not in presence_only and not version_eq(v, have[k])]
    out += [f'{k} {v} in the manifest, missing from {what}' for k, v in sorted(want.items()) if k not in have]
    out += [f'{k} {v} on {what}, not in the manifest' for k, v in sorted(have.items()) if k not in want]
    return out


def verify(path):
    if not OUT.exists():
        print(f'no {OUT}: run python scripts\\gen-mods.py')
        return 1
    want = {m: v for m, v, _ in rows(read(OUT))}
    if os.path.isdir(path):
        have = from_plugins(path)
        if BEPINEX_ID in want:
            want.pop(BEPINEX_ID)  # the pack installs to BepInEx\core, not plugins\
        problems = diff(want, have, 'the install')
    else:
        want = {n: v for m, v, n in rows(read(OUT)) if n}
        shims = {n for m, _, n in rows(read(OUT)) if m in NO_VERSION}
        unnamed = [m for m, _, n in rows(read(OUT)) if not n]
        problems = diff(want, from_log(path), 'the log', shims)
        for m in unnamed:
            print(f'note     {m} has no plugin name in the manifest; only a plugins\\ folder proves it')
    for p in problems:
        print('MISMATCH ' + p)
    print(f'{len(want)} mods checked against {path}: {len(problems)} mismatch(es)')
    return 1 if problems else 0


if __name__ == '__main__':
    if '--verify' in sys.argv:
        sys.exit(verify(sys.argv[sys.argv.index('--verify') + 1]))
    text = build()
    if '--check' in sys.argv:
        old = read(OUT) if OUT.exists() else ''
        if old == text:
            print(f'{OUT.name} matches the profile')
            sys.exit(0)
        want = {m: v for m, v, _ in rows(old)}
        have = {m: v for m, v, _ in rows(text)}
        for p in diff(want, have, 'the profile'):
            print('MISMATCH ' + p)
        print(f'{OUT.name} is stale: run python scripts\\gen-mods.py')
        sys.exit(1)
    with open(OUT, 'w', encoding='utf-8', newline='\r\n') as f:  # repo pins '* -text'
        f.write(text)
    print(f'wrote {OUT} ({sum(1 for _ in rows(text))} mods)')
