#!/usr/bin/env python3
r"""Generate the KG Marketplace collection log from loot\collection-log.csv. Never edit the cfgs by hand.

    python scripts\gen-collection-log.py            write the three cfgs
    python scripts\gen-collection-log.py --check    exit 0 = cfgs match the csv, 1 = stale
    python scripts\gen-collection-log.py --audit    exit 0 = every collectible is logged, 1 = drift

Table: loot\collection-log.csv  category, prefab, display   (category text = dialogue page; order = page order)

One Talk quest per row on the NPC "Halla the Skald" (Quests type, profile + dialogue collection_log):
unlocked by HasItem <prefab> 1, completes by talking, cooldown 36500 = once per character, item is kept.
The dialogue lists every row per category as a reply gated by QuestFinished, so found = lit, missing = greyed.

--audit: every collectible in the build (wackydb OSRS_* clones, non-coin items in loot\drops.csv, the five
Wizardry shards) must have a csv row, and every OSRS_* row must still be a clone. Superior drops are plain
materials and are not logged; trophies come from vanilla and are listed by hand.
Writes Quests\osrsheim_collection_log.cfg, QuestProfiles\osrsheim_collection_log.cfg,
Dialogues\osrsheim_collection_log.cfg under Marketplace\Configs.
"""
import csv
import glob
import os
import re
import sys
from pathlib import Path

from main_guard import require_current

ROOT = Path(__file__).resolve().parent.parent
LOOT = ROOT / 'loot'
CFG = Path(os.environ['APPDATA']) / 'com.kesomannen.gale/valheim/profiles/OSRSheim/BepInEx/config'
KG = CFG / 'Marketplace/Configs'
NPC = 'Halla the Skald'
PROFILE = 'collection_log'
OUT = {
    'quests': KG / 'Quests/osrsheim_collection_log.cfg',
    'profile': KG / 'QuestProfiles/osrsheim_collection_log.cfg',
    'dialogue': KG / 'Dialogues/osrsheim_collection_log.cfg',
}
HEAD = '# GENERATED by scripts\\gen-collection-log.py from loot\\collection-log.csv. Edit the csv and regenerate.\n'
# Currencies, not collectibles. WitheredBone is the Swamp prayer currency
# (Marketplace\Configs\Buffers\osrsheim_prayers.cfg), spent like coins.
NOT_COLLECTIBLE = {'Coins', 'Wood', 'WitheredBone'}


def fail(msg):
    print('ERROR', msg)
    sys.exit(1)


def slug(text):
    return re.sub(r'[^a-z0-9]+', '_', text.lower()).strip('_')


def rows():
    out = []
    with open(LOOT / 'collection-log.csv', newline='', encoding='utf-8') as f:
        for r in csv.DictReader(f):
            r = {k: (v or '').strip() for k, v in r.items()}
            if not r['prefab'] or r['category'].startswith('#'):
                continue
            if ',' in r['display'] or '|' in r['display']:
                fail(f'{r["prefab"]}: display text may not contain , or |')
            out.append(r)
    seen = set()
    for r in out:
        if r['prefab'] in seen:
            fail(f'collection-log.csv: {r["prefab"]} listed twice')
        seen.add(r['prefab'])
    return out


def qid(prefab):
    return 'log_' + slug(prefab)


def generate():
    data = rows()
    q = [HEAD, f'# {len(data)} entries. NPC: Type = Quests, Profile = {PROFILE}, Dialogue = {PROFILE}, Name Override = {NPC}.\n\n']
    for r in data:
        q.append(f'[{qid(r["prefab"])}]\nTalk\nLog: {r["display"]}\n'
                 f'Show Halla your {r["display"]} and she will write it into the saga.\n'
                 f'"{NPC}"\nItem: Coins, 1\n36500\nHasItem, {r["prefab"]}, 1\n\n')
    p = [HEAD, f'[{PROFILE}]\n' + ', '.join(qid(r['prefab']) for r in data) + '\n']
    cats = []
    for r in data:
        if r['category'] not in cats:
            cats.append(r['category'])
    d = [HEAD, f'[{PROFILE}]\nI am Halla. I keep the saga of everything found in Gielheim. Show me a thing and I will write it down.\n',
         f'Text: Record a find | Command: OpenUI, Quests, {PROFILE}\n']
    for c in cats:
        n = sum(1 for r in data if r['category'] == c)
        d.append(f'Text: {c} ({n}) | Transition: {PROFILE}_{slug(c)}\n')
    d.append(f'Text: Farewell | Transition: {PROFILE}_bye\n\n')
    for c in cats:
        d.append(f'[{PROFILE}_{slug(c)}]\n{c}: lit entries are in the saga. Grey ones are still out there.\n')
        for r in data:
            if r['category'] == c:
                d.append(f'Text: {r["display"]} | Condition: QuestFinished, {qid(r["prefab"])}\n')
        d.append(f'Text: Back | Transition: {PROFILE}\n\n')
    d.append(f'[{PROFILE}_bye]\nThe saga is never finished.\n')
    return {'quests': ''.join(q), 'profile': ''.join(p), 'dialogue': ''.join(d)}


def on_disk(key):
    p = OUT[key]
    return p.read_text(encoding='utf-8-sig') if p.exists() else ''


def collectibles():
    """Everything in the build a player can find and would want logged."""
    found = {}
    for f in glob.glob(str(CFG / 'wackysDatabase/Items/Item_*.yml')):
        m = re.search(r'^name:\s*(\S+)', open(f, encoding='utf-8-sig').read(), re.M)
        if m:
            found[m.group(1)] = 'wackydb clone'
    with open(LOOT / 'drops.csv', newline='', encoding='utf-8') as f:
        for r in csv.DictReader(f):
            item = (r['item'] or '').strip()
            if item and item not in NOT_COLLECTIBLE and not item.startswith('#'):
                found.setdefault(item, 'loot\\drops.csv')
    for b in ('Elder', 'Bonemass', 'Moder', 'Yagluth', 'Queen'):
        found.setdefault(f'Shard{b}_TW', 'Wizardry mage drop')
    return found


def audit():
    logged = {r['prefab'] for r in rows()}
    clones = {p for p, src in collectibles().items() if src == 'wackydb clone'}
    problems = []
    for prefab, src in sorted(collectibles().items()):
        if prefab not in logged:
            problems.append(f'{prefab} ({src}) has no row in loot\\collection-log.csv')
    for prefab in sorted(logged):
        if prefab.startswith('OSRS_') and prefab not in clones:
            problems.append(f'{prefab} is in loot\\collection-log.csv but no wackydb clone exists any more')
    return problems


def main():
    args = sys.argv[1:]
    if '--audit' in args:
        problems = audit()
        for p in problems:
            print('DRIFT', p)
        print(f'collection log audit: {len(problems)} problem(s)')
        sys.exit(1 if problems else 0)
    new = generate()
    if '--check' in args:
        stale = [k for k in OUT if on_disk(k) != new[k]]
        print(f'collection log cfgs {"stale: " + ", ".join(stale) if stale else "match the csv"}')
        sys.exit(1 if stale else 0)
    require_current(LOOT, __file__)
    for k, text in new.items():
        OUT[k].parent.mkdir(parents=True, exist_ok=True)
        OUT[k].write_text(text, encoding='utf-8')
    print(f'wrote {len(rows())} log entries to {", ".join(p.name for p in OUT.values())}')


if __name__ == '__main__':
    main()
