#!/usr/bin/env python3
r"""Generate the NPC placement set from reference\npc-layout.csv. Never edit the outputs by hand.

    python scripts\gen-npcs.py                         write every output
    python scripts\gen-npcs.py --check                 exit 0 = outputs match the layout, 1 = stale
    python scripts\gen-npcs.py --set <npc> <node> "<pos text>"   fill one row (any three numbers, rounded)
    python scripts\gen-npcs.py --town <x> <z> <heading>           lay Kaupang out around its square (TOWN plan); blanks every other row
    python scripts\gen-npcs.py --builder on|off        list the builder dialogue in DistancedUI (setup only)

Layout: reference\npc-layout.csv  npc, node, x, y, z. npc = a Marketplace_SavedNPCs template name.
Outputs (repo config\, push with scripts\sync-configs.ps1 -Push):
  Marketplace\Configs\CustomSpawnData\npc_<npc>_<node>.yml   type, profile, dialogue, name, fashion as ZDO keys
  Marketplace\Configs\Dialogues\osrsheim_builder.cfg          [osr_builder]: one reply spawns every placed row
  Marketplace\Configs\Teleporters\osrsheim_teleports.cfg      waystone rows -> their node (set-waystone.py)

KG Marketplace (10.0.1, DLL-read) `SpawnXYZWithData, MarketPlaceNPC, n, lvl, x, y, z, radius, key` instantiates
the NPC at int x y z with rotation 0 and writes CustomSpawnData\<key>.yml onto its ZDO; the NPC reads the
keys in Awake. Builder replies need SwordCheat in the inventory (spawn-only item). Open the builder with
Alt+` (DistancedUI) after --builder on; --builder off when done.
Biome waystones get KGnpcShowCondition: visible only to a character holding that oath or a higher one.
"""
import csv
import importlib.util
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
LAYOUT = ROOT / 'reference/npc-layout.csv'
TEMPLATES = ROOT / 'config/Marketplace_SavedNPCs'
MARKET = ROOT / 'config/Marketplace'
SPAWNDATA = MARKET / 'Configs/CustomSpawnData'
BUILDER = MARKET / 'Configs/Dialogues/osrsheim_builder.cfg'
DISTANCED = MARKET / 'DistancedUI/DistancedUI.cfg'
HEAD = '# GENERATED by scripts\\gen-npcs.py from reference\\npc-layout.csv. Edit the layout and regenerate.\n'
GATE = 'SwordCheat'
TP_OFFSET = (3, 1, 0)  # teleport lands beside the stone, not inside it
TOWN_R = 300  # rows this close to the Kaupang stone are placed in one click; the rest one by one on site

spec = importlib.util.spec_from_file_location('set_waystone', ROOT / 'scripts/set-waystone.py')
waystone = importlib.util.module_from_spec(spec)
spec.loader.exec_module(waystone)
OATHS = [k for k in waystone.NODES if k != 'kaupang']  # tier order

TYPES = {'None': 0, 'Trader': 1, 'Info': 2, 'Teleporter': 3, 'Feedback': 4, 'Banker': 5, 'Gambler': 6,
         'Quests': 7, 'Buffer': 8, 'Transmog': 9, 'Marketplace': 10, 'Mail': 11}
# template fashion field -> ZDO key, 'f' = float (NPC_Fashion.ApplyToZdo)
FASHION = {
    'LeftItem': 'KGleftItem', 'RightItem': 'KGrightItem', 'HelmetItem': 'KGhelmetItem', 'ChestItem': 'KGchestItem',
    'LegsItem': 'KGlegsItem', 'CapeItem': 'KGcapeItem', 'HairItem': 'KGhairItem', 'HairColor': 'KGhairItemColor',
    'LeftItemHidden': 'KGLeftItemBack', 'RightItemHidden': 'KGRightItemBack',
    'InteractAnimation': 'KGinteractAnimation', 'GreetAnimation': 'KGgreetingAnimation',
    'ByeAnimation': 'KGbyeAnimation', 'GreetText': 'KGgreetingText', 'ByeText': 'KGbyeText',
    'SkinColor': 'KGskinColor', 'CraftingAnimation': 'KGcraftingAnimation', 'BeardItem': 'KGbeardItem',
    'BeardColor': 'KGbeardColor', 'InteractAudioClip': 'KGinteractSound', 'PeriodicAnimation': 'KGperiodicAnimation',
    'PeriodicSound': 'KGperiodicSound',
    'TextSize': ('KGtextSize', 'f'), 'TextHeight': ('KGtextHeight', 'f'), 'ModelScale': ('KGnpcScale', 'f'),
    'PeriodicAnimationTime': ('KGperiodicAnimationTime', 'f'), 'PeriodicSoundTime': ('KGperiodicSoundTime', 'f'),
}
NUM = re.compile(r'-?\d+(?:\.\d+)?')
errors = []


def err(msg):
    errors.append(msg)
    print('ERROR ', msg)


def read_layout():
    with open(LAYOUT, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def write_layout(rows):
    with open(LAYOUT, 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=['npc', 'node', 'x', 'y', 'z'], lineterminator='\n')
        w.writeheader()
        w.writerows(rows)


def key(row):
    return 'npc_' + re.sub(r'[^a-z0-9]+', '_', f"{row['npc']}_{row['node']}".lower()).strip('_')


def placed(row):
    return all(row[c].strip() for c in 'xyz')


def show_condition(node):
    if node not in OATHS:
        return ''
    return ' || '.join(f'HasPlayerKey, oath_{k}' for k in OATHS[OATHS.index(node):])


def q(s):
    return json.dumps(str(s), ensure_ascii=False)


def spawn_yaml(row, t):
    main, fashion = t.get('main') or {}, t.get('fashion') or {}
    if main.get('Type') not in TYPES:
        err(f"{row['npc']}: Type {main.get('Type')!r} is not a KG NPC type")
    strings = {'KGnpcNameOverride': main.get('NameOverride') or row['npc'],
               'KGnpcProfile': main.get('Profile') or '', 'KGnpcDialogue': main.get('Dialogue') or '',
               'KGnpcModelOverride': main.get('Prefab') or '', 'KGmarketPinIcon': main.get('PinIcon') or ''}
    for field in ('KGnpcProfile', 'KGnpcDialogue'):
        if strings[field] != strings[field].lower():
            err(f"{row['npc']}: {field} {strings[field]!r} must be lower case (KG lower-cases lookups)")
    floats = {}
    for field, value in fashion.items():
        target = FASHION.get(field)
        if target is None:
            err(f"{row['npc']}: fashion field {field!r} has no ZDO key in gen-npcs.py FASHION")
        elif isinstance(target, tuple):
            floats[target[0]] = float(value or 0)
        elif value not in (None, ''):
            strings[target] = value
    cond = show_condition(row['node']) if row['npc'] == 'Waystone' else ''
    if cond:
        strings['KGnpcShowCondition'] = cond
    out = [HEAD.rstrip('\n'), f"# {row['npc']} @ {row['node']}",
           'Ints:', f"  KGmarketNPC: {TYPES.get(main.get('Type'), 0)}",
           'Bools:', f"  KGmarketPinned: {'true' if t.get('isPinned') else 'false'}",
           'Floats:'] + [f'  {k}: {v:g}' for k, v in sorted(floats.items())] + \
          ['Strings:'] + [f'  {k}: {q(v)}' for k, v in strings.items() if v != '']
    return '\n'.join(out) + '\n'


def spawn_cmd(row):
    x, y, z = (int(row[c]) for c in 'xyz')
    return f'Command: SpawnXYZWithData,MarketPlaceNPC,1,1,{x},{y},{z},0,{key(row)}'


def builder(rows):
    done = [r for r in rows if placed(r)]
    hub = next((r for r in done if (r['npc'], r['node']) == ('Waystone', 'kaupang')), None)
    near = [r for r in done if hub and (int(r['x']) - int(hub['x'])) ** 2 + (int(r['z']) - int(hub['z'])) ** 2 <= TOWN_R ** 2]
    far = [r for r in done if r not in near]
    gate = f'Condition: HasItem,{GATE},1 | AlwaysVisible: true | OverrideError: Carry {GATE}'
    lines = [HEAD.rstrip('\n'),
             '# Setup-only. Listed in DistancedUI (Alt+`) by gen-npcs.py --builder on; every reply needs ' + GATE + '.',
             '# SpawnXYZWithData never checks for an existing NPC: placing twice makes two. Remove with mnpcremove.',
             f'# A client only syncs ZDOs near itself: place far rows while standing there (Go, then Place).',
             '[osr_builder]',
             f'Builder. {len(done)} of {len(rows)} layout rows have coordinates: {len(near)} in Kaupang and {len(far)} far.']
    if near:
        lines.append(f'Text: Place Kaupang ({len(near)} NPCs) | ' + ' | '.join(spawn_cmd(r) for r in near) + f' | {gate}')
    if far:
        lines.append('Text: Far NPCs | Transition: osr_builder_far')
    lines += ['Text: Oath keys (testing) | Transition: osr_builder_keys', '', '[osr_builder_far]', 'Go there first. Then place.']
    for r in far:
        x, y, z = (int(r[c]) for c in 'xyz')
        lines.append(f"Text: Go to {r['npc']} at {r['node']} | Command: Teleport,{x + 3},{y + 2},{z},true | {gate}")
        lines.append(f"Text: Place {r['npc']} at {r['node']} | {spawn_cmd(r)} | {gate}")
    lines += ['Text: Back | Transition: osr_builder', '', '[osr_builder_keys]', 'Oath keys on this character.']
    for k in OATHS:
        lines.append(f'Text: Give oath_{k} | Command: AddPlayerKey,oath_{k} | {gate} | Transition: osr_builder_keys')
    lines.append('Text: Clear every oath key | '
                 + ' | '.join(f'Command: RemovePlayerKey,oath_{k}' for k in OATHS) + f' | {gate} | Transition: osr_builder_keys')
    lines += ['Text: Talk to a waystone | Transition: waystone', 'Text: Talk to Sigrun | Transition: oath_keeper',
              'Text: Back | Transition: osr_builder']
    return '\n'.join(lines) + '\n'


def teleports(rows):
    text = waystone.CFG.read_text(encoding='utf-8')
    for r in rows:
        if r['npc'] != 'Waystone':
            continue
        if r['node'] not in waystone.NODES:
            err(f"Waystone node {r['node']!r} is not a set-waystone.py node")
            continue
        if placed(r):
            x, y, z = (int(r[c]) + d for c, d in zip('xyz', TP_OFFSET))
            text = waystone.render(r['node'], x, y, z, text)
        else:
            text = waystone.unset(r['node'], text)
    return text


def outputs():
    rows = read_layout()
    templates = {p.stem: yaml.safe_load(p.read_text(encoding='utf-8')) for p in TEMPLATES.glob('*.yml')}
    seen = set()
    files = {}
    for r in rows:
        if r['npc'] not in templates:
            err(f"layout npc {r['npc']!r} has no template in {TEMPLATES.name}")
            continue
        if key(r) in seen:
            err(f'duplicate layout row {key(r)}')
        seen.add(key(r))
        for c in 'xyz':
            if r[c].strip() and not re.fullmatch(r'-?\d+', r[c].strip()):
                err(f'{key(r)}: {c}={r[c]!r} is not a whole number (KG int.Parse)')
        files[SPAWNDATA / f'{key(r)}.yml'] = (spawn_yaml(r, templates[r['npc']]), '\n')
    unused = set(templates) - {r['npc'] for r in rows}
    if unused:
        err(f'templates not in the layout: {sorted(unused)}')
    if not errors:
        files[BUILDER] = (builder(rows), '\r\n')
        files[waystone.CFG] = (teleports(rows), '\n')
    return files


def read(p, nl):
    return p.read_bytes().decode('utf-8').replace(nl, '\n') if p.exists() else None


def set_row(npc, node, text):
    nums = NUM.findall(text)
    if len(nums) != 3:
        sys.exit(f'ERROR need three numbers in the pos text, found {nums}')
    rows = read_layout()
    hit = [r for r in rows if r['npc'].lower() == npc.lower() and r['node'].lower() == node.lower()]
    if not hit:
        sys.exit(f'ERROR no layout row {npc} / {node}')
    hit[0].update(zip('xyz', (str(int(round(float(n)))) for n in nums)))
    write_layout(rows)
    print(f"ok    {hit[0]['npc']} @ {node} -> {hit[0]['x']}, {hit[0]['y']}, {hit[0]['z']}")


# Kaupang plan: (right, forward) metres from the square; forward = towards the harbour water.
TOWN = {
    ('Waystone', 'kaupang'): (0, 14), ('Sigrun the Oathkeeper', 'town'): (5, 12),    # the quay
    ('Seeress', 'town'): (-13, 11),                                                  # völva by the sea
    ('Kaupang', 'town'): (0, 3), ('Halla the Skald', 'town'): (-4, -2),              # the square
    ('Shopkeeper', 'town'): (-9, 5), ('Gullveig', 'town'): (-9, 0), ('Herbwife', 'town'): (-9, -5),
    ('Banker', 'town'): (9, 5), ('Verdandi the Weaver', 'town'): (9, 0), ('Gambler', 'town'): (9, -5),
    ('Ragnar the Bold', 'town'): (14, -9),                                           # flower patch
    ('Ulfar the Guide', 'town'): (-3, -15), ('Gielheim Guide', 'town'): (3, -15),    # landward gate
    ('Huntmaster Hrafn', 'town'): (13, -15), ('Gothi Eirik', 'town'): (-14, -12),    # woods edge, shrine
}


def town(cx, cz, heading):
    """Lay out Kaupang around the square at cx, cz; heading = compass degrees to the water (0 = +z, 90 = +x)."""
    import math
    h = math.radians(heading)
    fwd, right = (math.sin(h), math.cos(h)), (math.cos(h), -math.sin(h))
    rows = read_layout()
    n = 0
    for r in rows:
        off = TOWN.get((r['npc'], r['node']))
        if off:
            r.update(x=str(round(cx + off[0] * right[0] + off[1] * fwd[0])), y='',
                     z=str(round(cz + off[0] * right[1] + off[1] * fwd[1])))
            n += 1
        else:
            r.update(x='', y='', z='')
    write_layout(rows)
    print(f'ok    {n} Kaupang rows around {cx}, {cz}, water at {heading} deg; y blank until measured')
    print(f'      {len(rows) - n} far rows blanked: measure on site with --set')


def toggle_builder(on):
    b = DISTANCED.read_bytes()
    m = re.search(rb'^Dialogues = (.*?)\r?$', b, re.M)
    names = [n.strip() for n in m.group(1).decode().split(',') if n.strip() and n.strip() != 'osr_builder']
    names += ['osr_builder'] if on else []
    new = b[:m.start(1)] + ', '.join(names).encode() + b[m.end(1):]
    DISTANCED.write_bytes(new)
    print(f"ok    DistancedUI Dialogues = {', '.join(names)}")


def main():
    a = sys.argv[1:]
    if a[:1] == ['--set'] and len(a) == 4:
        return set_row(a[1], a[2], a[3])
    if a[:1] == ['--town'] and len(a) == 4:
        return town(float(a[1]), float(a[2]), float(a[3]))
    if a[:1] == ['--builder'] and len(a) == 2 and a[1] in ('on', 'off'):
        return toggle_builder(a[1] == 'on')
    if a and a != ['--check']:
        sys.exit(__doc__)
    files = outputs()
    if errors:
        sys.exit(1)
    stale = [p for p, (text, nl) in files.items() if read(p, nl) != text]
    extra = [p for p in SPAWNDATA.glob('npc_*.yml') if p not in files] if SPAWNDATA.exists() else []
    if '--check' in a:
        for p in stale + extra:
            print('STALE ', p.relative_to(ROOT))
        if not stale and not extra:
            print(f'{len(files)} outputs match the npc layout')
        sys.exit(1 if stale or extra else 0)
    SPAWNDATA.mkdir(parents=True, exist_ok=True)
    for p in extra:
        p.unlink()
    for p in stale:
        p.write_bytes(text_bytes(*files[p]))
    rows = read_layout()
    print(f'ok    {len(files) - 2} spawn files, builder with {sum(placed(r) for r in rows)}/{len(rows)} placed rows; '
          f'{len(stale)} written, {len(extra)} removed')


def text_bytes(text, nl):
    return text.replace('\n', nl).encode('utf-8')


if __name__ == '__main__':
    main()
