#!/usr/bin/env python3
r"""Generate the in-game handbook (a KG Marketplace dialogue tree) from loot\*.csv. Never edit the cfg by hand.

    python scripts\gen-handbook.py            write Dialogues\osrsheim_handbook.cfg
    python scripts\gen-handbook.py --check    exit 0 = cfg matches the tables, 1 = stale

Pages: [handbook] root (Gielheim Guide NPC, also DistancedUI) -> bestiary -> biome -> creature.
A creature page lists every modded drop with the chance the player actually gets: csv chance x the
owner's class multiplier, the same maths as gen-loot.py. Shared gem / rare tables are merged in, superior
bonus loot (update-superiors.py ROWS) gets a sub-page. Vanilla drops are untouched and not listed.
Every drop line is tinted by rarity (TIERS); the bestiary page carries the key.
Names: creatures.csv `display` (variants with identical drops share one page), collection-log.csv
`display`, VANILLA below; an unnamed item fails the run.
Writes to the repo config\ (source of truth); push with scripts\sync-configs.ps1 -Push.
"""
import csv
import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOOT = ROOT / 'loot'
OUT = ROOT / 'config/Marketplace/Configs/Dialogues/osrsheim_handbook.cfg'
HEAD = '# GENERATED by scripts\\gen-handbook.py from loot\\*.csv. Edit the tables and regenerate.\n'
P = 'handbook'
VANILLA = {
    'Amber': 'Amber', 'AmberPearl': 'Amber pearl', 'Chain': 'Chain', 'Coins': 'Coins', 'Crystal': 'Crystal',
    'GoldOre': 'Gold ore', 'Ruby': 'Ruby', 'SilverNecklace': 'Silver necklace', 'Wood': 'Wood',
    'FineWood': 'Fine wood', 'Resin': 'Resin', 'BoneFragments': 'Bone fragments', 'Feathers': 'Feathers',
    'Entrails': 'Entrails', 'IronScrap': 'Scrap iron', 'WolfPelt': 'Wolf pelt', 'WolfFang': 'Wolf fang',
    'BlackMetalScrap': 'Black metal scrap', 'Needle': 'Needle', 'Carapace': 'Carapace', 'ScaleHide': 'Scale hide',
    'CharredBone': 'Charred bone', 'FlametalOreNew': 'Flametal ore', 'WitheredBone': 'Withered bone',
}
# Rarity colours (TMP rich text): threshold %, hex, legend line. COLOUR = False drops every tag.
COLOUR = True
TIERS = [(50, 'b8b8b8', 'Common - 50% or better'),
         (10, '5ad46a', 'Uncommon - 10% to 50%'),
         (2, '4da3ff', 'Rare - 1 in 10 to 1 in 50'),
         (0.5, 'c77dff', 'Very rare - 1 in 50 to 1 in 200'),
         (0, 'ffb300', 'Ultra rare - rarer than 1 in 200')]
BOSS = {'defeated_eikthyr': 'Eikthyr', 'defeated_gdking': 'the Elder', 'defeated_bonemass': 'Bonemass',
        'defeated_dragon': 'Moder', 'defeated_goblinking': 'Yagluth', 'defeated_queen': 'the Queen',
        'defeated_fader': 'Fader', 'defeated_frozenking_p3': 'the Frost King'}


def fail(msg):
    print('ERROR', msg)
    sys.exit(1)


def module(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / 'scripts' / f'{name}.py')
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def slug(text):
    return re.sub(r'[^a-z0-9]+', '_', text.lower()).strip('_')


def text(s):
    if ',' in s or '|' in s:
        fail(f'reply text may not contain , or | : {s!r}')
    return s


def item_names():
    names = dict(VANILLA)
    with open(LOOT / 'collection-log.csv', newline='', encoding='utf-8') as f:
        for r in csv.DictReader(f):
            if r['prefab'] and not r['category'].startswith('#'):
                names[r['prefab'].strip()] = r['display'].strip()
    return names


def colour(s, p):
    if not COLOUR:
        return s
    hexcode = next(t[1] for t in TIERS if p >= t[0])
    return f'<color=#{hexcode}>{s}</color>'


def odds(p):
    if p >= 100:
        return 'always'
    if p >= 10:
        return f'{p:.0f}%' if p == int(p) else f'{p:.1f}%'
    return f'1 in {round(100 / p)}'


def row(names, item, lo, hi, p, one=False, key=None):
    name = names.get(item) or fail(f'no display name for item {item} (VANILLA or collection-log.csv)')
    amt = '' if lo == hi == 1 else f' x{lo}' if lo == hi else f' {lo}-{hi}'
    tail = f' (after {BOSS.get(key, key)})' if key else ''
    tail += ' (one each)' if one else ''
    return f'Text: {colour(text(name + amt + " " + odds(p) + tail), p)}\n'


def drop_rows(names, rows, mult, loot):
    out = []
    for r in rows:
        flags = set(r['flags'].split())
        key = next((f[4:] for f in flags if f.startswith('key=')), None)
        p = loot.chance(r['chance'], mult, 'time')
        out.append(row(names, r['item'], int(r['min']), int(r['max']), p, 'one-per-player' in flags, key))
    return out


def generate():
    loot = module('gen-loot')
    sup = {r[0]: r for r in module('update-superiors').ROWS}
    classes, creatures, lists, drops = loot.load('time', None)
    names = item_names()
    for c in creatures:
        if not c.get('display'):
            fail(f'creatures.csv {c["creature"]}: no display name')
    # (biome, display) -> page; variants must carry identical drops to share a page.
    pages, order, biomes = {}, [], []
    for c in creatures:
        key = (c['biome'], c['display'])
        sig = (c['list'], c['class'], tuple(tuple(r[k] for k in ('item', 'min', 'max', 'chance', 'flags')) for r in drops.get(c['creature'], [])))
        if key in pages:
            if pages[key]['sig'] != sig:
                fail(f'{c["creature"]}: display {c["display"]!r} already used in {c["biome"]} with different drops')
            pages[key]['prefabs'].append(c['creature'])
            continue
        pages[key] = {'c': c, 'sig': sig, 'prefabs': [c['creature']]}
        order.append(key)
        if c['biome'] not in biomes:
            biomes.append(c['biome'])
    node = {k: f'{P}_c_{slug(k[0])}_{slug(k[1])}' for k in order}

    d = [HEAD, f'# NPC: Type = Info, Profile = gielheim_guide, Dialogue = {P}, Name Override = Gielheim Guide. Also in DistancedUI.\n\n',
         f'[{P}]\nI am the Gielheim Guide. Ask and I will tell you how this world works.\n',
         'Text: The rules of Gielheim | Command: OpenUI, Info, gielheim_guide\n',
         f'Text: The bestiary | Transition: {P}_bestiary\n',
         f'Text: Farewell | Transition: {P}_bye\n\n',
         f'[{P}_bestiary]\nEvery creature and what it drops beyond the usual spoils. Chances are what you will see. Uniques roll once per kill, pets once per player.\n']
    for t in TIERS if COLOUR else []:
        d.append(f'Text: {colour(t[2], t[0])}\n')
    for b in biomes:
        n = sum(1 for k in order if k[0] == b)
        d.append(f'Text: {text(b)} ({n}) | Transition: {P}_b_{slug(b)}\n')
    d.append(f'Text: Back | Transition: {P}\n\n')
    for b in biomes:
        d.append(f'[{P}_b_{slug(b)}]\n{b}. Choose a creature.\n')
        for k in order:
            if k[0] == b:
                d.append(f'Text: {text(k[1])} | Transition: {node[k]}\n')
        d.append(f'Text: Back | Transition: {P}_bestiary\n\n')
    for k in order:
        pg = pages[k]
        c = pg['c']
        d.append(f'[{node[k]}]\n{k[1]} ({k[0]}). Extra drops on top of the usual spoils.\n')
        d += drop_rows(names, drops.get(c['creature'], []), classes[c['class']], loot)
        if c['list']:
            d += drop_rows(names, drops.get(c['list'], []), classes[c['class']], loot)
        s = next((sup[p] for p in pg['prefabs'] if p in sup), None)
        if s:
            d.append(f'Text: Superior loot | Transition: {node[k]}_superior\n')
        d.append(f'Text: Back | Transition: {P}_b_{slug(b := k[0])}\n\n')
        if s:
            creature, key, low, high, gem, gl, gh, material, extra, rare, rate = s
            d.append(f'[{node[k]}_superior]\nA superior {k[1]} after {BOSS[key]} also drops all of this on top. A common two-star does not.\n')
            d.append(row(names, 'Coins', low, high, 100))
            d.append(row(names, gem, gl, gh, 30))
            d.append(row(names, material, 2, 4, 40))
            d.append(row(names, extra, 1, 2, 20))
            d.append(row(names, rare, 1, 1, rate))
            d.append(f'Text: Back | Transition: {node[k]}\n\n')
    d.append(f'[{P}_bye]\nThe book is always open.\n')
    return ''.join(d)


def main():
    new = generate()
    if '--check' in sys.argv:
        cur = OUT.read_text(encoding='utf-8-sig') if OUT.exists() else ''
        print('handbook cfg ' + ('matches loot\\*.csv' if cur == new else 'stale: run python scripts\\gen-handbook.py'))
        sys.exit(0 if cur == new else 1)
    OUT.write_text(new, encoding='utf-8', newline='\r\n')
    print(f'wrote {OUT.name}: {new.count(chr(10) + "[")} nodes')


if __name__ == '__main__':
    main()
