isPinned: false
main:
  Type: Quests
  NameOverride: Sigrun the Oathkeeper
  Profile: oath_keeper
  Prefab: ''
  Dialogue: oath_keeper
  PinIcon: ''
  IMAGE: ''
fashion:
  LeftItem: ''
  RightItem: ''
  HelmetItem: ''
  ChestItem: ''
  LegsItem: ''
  CapeItem: ''
  HairItem: ''
  HairColor: ''
  ModelScale: 1
  LeftItemHidden: ''
  RightItemHidden: ''
  InteractAnimation: ''
  GreetAnimation: ''
  ByeAnimation: ''
  GreetText: ''
  ByeText: ''
  SkinColor: ''
  CraftingAnimation: ''
  BeardItem: ''
  BeardColor: ''
  InteractAudioClip: ''
  TextSize: 3
  TextHeight: 0
  PeriodicAnimation: ''
  PeriodicAnimationTime: 0
  PeriodicSound: ''
  PeriodicSoundTime: 0
