isPinned: false
main:
  Type: Trader
  NameOverride: Verdandi the Weaver
  Profile: vanity_tailor
  Prefab: ''
  Dialogue: wise_old_man
  PinIcon: ''
  IMAGE: ''
fashion:
  LeftItem: ''
  RightItem: ''
  HelmetItem: ''
  ChestItem: ''
  LegsItem: ''
  CapeItem: ''
  HairItem: ''
  HairColor: ''
  ModelScale: 1
  LeftItemHidden: ''
  RightItemHidden: ''
  InteractAnimation: ''
  GreetAnimation: ''
  ByeAnimation: ''
  GreetText: ''
  ByeText: ''
  SkinColor: ''
  CraftingAnimation: ''
  BeardItem: ''
  BeardColor: ''
  InteractAudioClip: ''
  TextSize: 3
  TextHeight: 0
  PeriodicAnimation: ''
  PeriodicAnimationTime: 0
  PeriodicSound: ''
  PeriodicSoundTime: 0
